export const Actions = {
  SET_GAME_FIELD: 'SET_GAME_FIELD',
  SET_CURRENT_PLAYER: 'SET_CURRENT_PLAYER',
  SET_ISGAME_ENDED: 'SET_ISGAME_ENDED',
  SET_ISDRAW: 'SET_ISDRAW',
  RESTART_GAME: 'RESTART_GAME',
}
